import { describe, expect, it } from 'vitest';
import { createCircuitContext, createConstructorContext, dummyContractAddress, sampleUserAddress } from '@midnight-ntwrk/compact-runtime';
import { Contract, ledger, pureCircuits } from '../../contracts/managed/astraloom/contract/index.js';
const bytes = (n: number) => new Uint8Array(32).fill(n); const NOW = 1_800_000_000; const deadline = BigInt(NOW + 3600); const operator = bytes(9); const operatorHash = pureCircuits.operator_public_key(operator); const user = sampleUserAddress();
function setup(options: { threshold?: bigint; constellation?: Uint8Array; deadline?: bigint; hash?: Uint8Array; capacity?: bigint } = {}) { let signal = 90n, markerSecret = bytes(1), admin = operator; const contract = new Contract<undefined>({ private_signal: () => [undefined, signal], private_marker_secret: () => [undefined, markerSecret], operator_secret: () => [undefined, admin] }); let state = contract.initialState(createConstructorContext(undefined, user), options.threshold ?? 72n, options.constellation ?? bytes(2), options.deadline ?? deadline, bytes(3), options.hash ?? operatorHash, options.capacity ?? 10n).currentContractState.data; const context = (time = NOW) => createCircuitContext(dummyContractAddress(), user, state, undefined, undefined, undefined, time); const apply = (result: any) => { state = result.context.currentQueryContext.state; return ledger(state); }; return { contract, context, apply, read: () => ledger(state), witness: (s = 90n, secret = bytes(1), auth = operator) => { signal = s; markerSecret = secret; admin = auth; }, weave: (time = NOW) => apply(contract.circuits.weave_signal(context(time))), retune: (id = bytes(4), capacity = 10n, time = deadline, threshold = 80n) => apply(contract.circuits.retune_loom(context(), threshold, id, time, bytes(5), capacity)) }; }
describe('Astraloom compiled runtime', () => {
  it('initializes public policy and edition', () => { const state = setup().read(); expect(state.signal_threshold).toBe(72n); expect(state.signal_capacity).toBe(10n); expect(state.verified_signals).toBe(0n); expect(state.loom_active).toBe(true); expect(state.used_constellations.member(bytes(2))).toBe(true); expect(new TextDecoder().decode(state.edition).replace(/\0/g, '')).toBe('Astraloom:v1.0'); });
  it.each([[{ threshold: 101n }, /threshold/i], [{ capacity: 0n }, /capacity/], [{ deadline: 0n }, /positive/], [{ constellation: bytes(0) }, /Constellation/], [{ hash: bytes(0) }, /Operator/]] as const)('rejects malformed constructor configuration %#', (options, error) => expect(() => setup(options)).toThrow(error));
  it('accepts the exact threshold and writes only a marker receipt', () => { const h = setup(); h.witness(72n); const state = h.weave(); const marker = pureCircuits.make_signal_marker(bytes(1), bytes(2)); expect(state.verified_signals).toBe(1n); expect(state.spent_markers.member(marker)).toBe(true); expect(state.signal_log.lookup(marker)).toEqual(bytes(2)); expect('signal' in state).toBe(false); });
  it.each([71n, 101n])('rejects a signal outside the allowed range: %s', signal => { const h = setup(); h.witness(signal); expect(() => h.weave()).toThrow(/threshold|Signal/); expect(h.read().verified_signals).toBe(0n); });
  it('blocks marker reuse for the same constellation', () => { const h = setup(); h.weave(); expect(() => h.weave()).toThrow(/already been woven/); });
  it('enforces capacity and pause/resume', () => { const h = setup({ capacity: 1n }); h.weave(); h.witness(90n, bytes(8)); expect(() => h.weave()).toThrow(/capacity/); h.apply(h.contract.circuits.pause_loom(h.context())); expect(() => h.weave()).toThrow(/paused/); expect(() => h.contract.circuits.resume_loom(h.context())).toThrow(/capacity/); });
  it('enforces the closing time', () => { expect(setup().weave(Number(deadline) - 1).verified_signals).toBe(1n); for (const time of [Number(deadline), Number(deadline) + 1]) expect(() => setup().weave(time)).toThrow(/closed/); });
  it('rejects incorrect operator and preserves history on retune', () => { const h = setup(); h.witness(90n, bytes(1), bytes(7)); expect(() => h.contract.circuits.pause_loom(h.context())).toThrow(/authorization/); h.witness(); h.weave(); const state = h.retune(); expect(state.verified_signals).toBe(1n); expect(state.signal_threshold).toBe(80n); expect(state.operator_commitment).toEqual(operatorHash); expect(state.spent_markers.size()).toBe(1n); });
  it('rejects reused constellation IDs and invalid retunes', () => { const h = setup(); expect(() => h.retune(bytes(2))).toThrow(/already used/); h.weave(); expect(() => h.retune(bytes(4), 1n)).toThrow(/capacity/i); expect(() => h.retune(bytes(0))).toThrow(/nonzero/); });
  it('allows a different self-chosen marker secret; this is not Sybil resistance', () => { const h = setup(); h.weave(); h.witness(90n, bytes(6)); expect(h.weave().verified_signals).toBe(2n); });
});
