import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { Circle, LogOut, Menu, Moon, Orbit, Sun, X, ArrowUpRight, AlertCircle } from 'lucide-react';
import { useWallet } from './contexts/WalletContext';
import { CONFIG_EVENT, getNetwork, setNetwork } from './config';
import LandingPage from './pages/LandingPage';
const SignalPage = lazy(() => import('./pages/SignalPage'));
const AdminPage = lazy(() => import('./pages/AdminPage'));
const OperatorPage = lazy(() => import('./pages/OperatorPage'));
const AtlasPage = lazy(() => import('./pages/AtlasPage'));
const PrivacyPage = lazy(() => import('./pages/PrivacyPage'));

function initialTheme(): 'day' | 'night' { try { const stored = localStorage.getItem('ASTRALOOM_THEME'); if (stored === 'day' || stored === 'night') return stored; } catch { /* no storage */ } return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'night' : 'day'; }
function Wordmark() { return <span className="wordmark"><span className="wordmark-orbit"><Orbit size={19} strokeWidth={1.5} /></span><span>Astraloom<small>private signal studio</small></span></span>; }
export default function App() {
  const { address, isConnected, connect, disconnect, isConnecting, walletStatus, walletName, availableWallets, error, clearError } = useWallet();
  const [theme, setTheme] = useState(initialTheme); const [network, updateNetwork] = useState(getNetwork); const [mobileOpen, setMobileOpen] = useState(false); const [selectedWallet, setSelectedWallet] = useState(''); const menuButton = useRef<HTMLButtonElement>(null); const location = useLocation();
  useEffect(() => { document.documentElement.dataset.theme = theme; try { localStorage.setItem('ASTRALOOM_THEME', theme); } catch { /* keep in memory */ } }, [theme]);
  useEffect(() => { const sync = () => updateNetwork(getNetwork()); window.addEventListener(CONFIG_EVENT, sync); window.addEventListener('storage', sync); return () => { window.removeEventListener(CONFIG_EVENT, sync); window.removeEventListener('storage', sync); }; }, []);
  useEffect(() => { setMobileOpen(false); const titles: Record<string, string> = { '/': 'Private signals, composed in public', '/signal': 'Weave a private signal', '/atlas': 'Public atlas', '/privacy': 'Privacy boundaries', '/operator': 'Operator console', '/admin': 'Deployment studio' }; document.title = `${titles[location.pathname] || 'Unknown orbit'} · Astraloom`; window.scrollTo({ top: 0, behavior: 'instant' }); }, [location.pathname]);
  useEffect(() => { if (!mobileOpen) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMobileOpen(false); menuButton.current?.focus(); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [mobileOpen]);
  const changeNetwork = (value: 'preview' | 'preprod') => { disconnect(); setNetwork(value); updateNetwork(value); }; const short = address ? `${address.slice(0, 6)}…${address.slice(-4)}` : '';
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a><header className="topbar"><Link to="/" aria-label="Astraloom home"><Wordmark /></Link><nav id="primary-navigation" className={`main-nav ${mobileOpen ? 'open' : ''}`} aria-label="Primary navigation"><NavLink to="/signal">Weave signal</NavLink><NavLink to="/atlas">Public atlas</NavLink><NavLink to="/privacy">Privacy map</NavLink><NavLink to="/operator">Operator</NavLink></nav><div className="topbar-tools"><label className="network-select"><Circle size={8} fill="currentColor" aria-hidden="true" /><span className="sr-only">Midnight network</span><select value={network} onChange={event => changeNetwork(event.target.value as 'preview' | 'preprod')} disabled={isConnecting}><option value="preview">Preview</option><option value="preprod">Preprod</option></select></label><button className="icon-button" onClick={() => setTheme(theme === 'night' ? 'day' : 'night')} aria-label={`Switch to ${theme === 'night' ? 'day' : 'night'} mode`} title={`Switch to ${theme === 'night' ? 'day' : 'night'} mode`}>{theme === 'night' ? <Sun size={18} /> : <Moon size={18} />}</button>{isConnected ? <button className="wallet-pill" onClick={disconnect} aria-label={`Disconnect ${walletName || 'wallet'} ${short}`}><span className="live-dot" />{short}<LogOut size={15} /></button> : <button className="wallet-pill connect" onClick={() => void connect(network, selectedWallet || undefined)} disabled={isConnecting}>{isConnecting ? 'Connecting…' : 'Connect wallet'}<ArrowUpRight size={15} /></button>}<button ref={menuButton} className="icon-button menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-expanded={mobileOpen} aria-controls="primary-navigation" aria-label={mobileOpen ? 'Close navigation' : 'Open navigation'}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    {!isConnected && availableWallets.length > 1 && <div className="wallet-choice"><label htmlFor="wallet-choice">Wallet</label><select id="wallet-choice" value={selectedWallet} onChange={event => setSelectedWallet(event.target.value)}><option value="">Default detected</option>{availableWallets.map(wallet => <option value={wallet.id} key={wallet.id}>{wallet.name}</option>)}</select><span>Use Lace or 1AM for a real network session.</span></div>}
    {error && <div className="alert-bar" role="alert"><AlertCircle size={18} /><span>{error}</span><button className="icon-button" onClick={clearError} aria-label="Dismiss wallet error"><X size={17} /></button></div>}
    <main id="main-content" tabIndex={-1}><Suspense fallback={<div className="page loading-state">Mapping the next orbit…</div>}><Routes><Route path="/" element={<LandingPage />} /><Route path="/signal" element={<SignalPage />} /><Route path="/atlas" element={<AtlasPage />} /><Route path="/privacy" element={<PrivacyPage />} /><Route path="/operator" element={<OperatorPage />} /><Route path="/admin" element={<AdminPage />} /><Route path="*" element={<div className="page"><div className="page-heading"><span className="eyebrow">Coordinates unavailable</span><h1>This orbit is quiet.</h1><p>That address does not resolve. Return to the observatory and choose another path.</p><Link className="button primary" to="/">Return to Astraloom</Link></div></div>} /></Routes></Suspense></main>
    <footer className="footer"><div><Link to="/"><Wordmark /></Link><p>A privacy-first signal layer for Midnight builders who want proof without a dossier.</p></div><nav aria-label="Footer navigation"><Link to="/privacy">Privacy map</Link><Link to="/admin">Deployment studio</Link><Link to="/operator">Operator console</Link></nav><div className="footer-meta"><span><span className="live-dot" />{network} network</span><small>Experimental software · selective disclosure by design</small>{walletStatus === 'not-found' && <small>Install a Midnight-compatible wallet to transact.</small>}</div></footer>
  </div>;
}
